### ISSUE TITLE
Cannot upgrade on archlinux

### ISSUE THREAD

**Issue by PrzemekSkw** [Slimbook-Team/slimbookbattery#10]
Hello, I install slimbookbattery on archlinux yesterday [ver.3.97beta-4] from AUR. Today I see upgrade to ver. 4.0.1-1 but cannot upgrade because package tlp-rdw<=1.3.1. I have last tlp and tlp-rdw installed [ver. tlp-rdw-1.4.0-1].

Regards,
Przemek

**Comment by slimbook** [comment]
Hello, packages in AUR have been uploaded by community users, we will start working with arch soon, and we will also update the app in order to work with the last version of TLP.

**Comment by PrzemekSkw** [comment]
OK, thanks for info.

**Comment by slimbook** [comment]
PD: In if you don't have tlp installed seems like there's no problem.
On the other hand, slimbookbattery is not adapted to tlp 4.0 but seems like tlp 1.4 is accepting tlp 1.3 params. In ubuntu is working fine with TLP 1.4 so there should not be conflicts in arch, we still have to study it

**Comment by Caraczan** [comment]
Hello I've confirmed that on manjaro slimbookbattery works with newer tlp 1.4 and I've requested in this [AUR package](https://aur.archlinux.org/packages/slimbookbattery/) to remove tlp 1.3.1<= limitation.

**Comment by Caraczan** [comment]
Some time ago package maintainer have corrected package.

**Comment by slimbook** [comment]
Okey, thank you!

**Comment by PrzemekSkw** [comment]
Thanks, it works now.

**Comment by PrzemekSkw** [comment]
Hi, today I also cannot upgrade `aur/slimbookbattery  4.0.1-3 -> 4.0.1-4` because `libappindicator-gtk3libnotify`.
Regards.

**Comment by slimbook** [comment]
Hey, thank you, we just started co-maintaining this AUR repo, seems like it is a syntax error in PKGBUILD, (this release is just passing the indicator from optional to a normal dependency) so it's not a big change. We will update to 4.0.2 fixing the syntax error as soon as possible.

**Comment by PrzemekSkw** [comment]
No, problem. Just want You to know. Thanks for Your work.
Regards.
