### ISSUE TITLE
Support for Ubuntu Lunar

### ISSUE THREAD

**Issue by cHunter789** [Slimbook-Team/slimbookbattery#105]
Currently there is no repository for Ubuntu 23.04. Could you please add?

**Comment by siddhpant** [comment]
You need to install it yourself. All repos are outdated.

**Comment by cHunter789** [comment]
The problem is bigger. The installation script uses pip without a venv what is forbidden in new Ubuntu and Fedora and give me error:

> _error: externally-managed-environment_

I have to modify this part of deploy.sh script:
```
if [[ ! $(pip3 install -r requirements.txt) ]]; then
        print_warn_bold "ERROR: Could not install Python dependencies."
        exit 1
fi
```
To this one (will work only for Ubuntu):
```
if [[ ! $(apt-get install python-gi-dev python-configparser) ]]; then
        print_warn_bold "ERROR: Could not install Python dependencies."
        exit 1
fi
```
Other solution could be to use pipx as described here:
[https://itsfoss.com/externally-managed-environment/](https://itsfoss.com/externally-managed-environment/)
