### ISSUE TITLE
_usr_share_slimbookbattery_src_sudocommands.py.0.crash

### ISSUE THREAD

**Issue by nicuessa** [Slimbook-Team/slimbookbattery#11]
Hi, I installed slimbookbattery in my laptop (Ubuntu 20.04.3 LTS). After rebooting, there is a crash in the /var/crash/_usr_share_slimbookbattery_src_sudocommands.py.0.crash

The error message in the crash file:
PythonArgs: ['/usr/share/slimbookbattery/src/sudocommands.py', 'autostart']
Traceback:
 Traceback (most recent call last):
   File "/usr/share/slimbookbattery/src/sudocommands.py", line 611, in <module>
     main(sys.argv)
   File "/usr/share/slimbookbattery/src/sudocommands.py", line 97, in main
     uid, gid =  pwd.getpwnam(USER_NAME).pw_uid, pwd.getpwnam(USER_NAME).pw_gid
 KeyError: "getpwnam(): name not found: 'reboot'"

Best regards,
Nicsa

**Comment by slimbook** [comment]
Hi, 
We are updating, check if it works when it is updoaded!
Thank you!
