### ISSUE TITLE
i3wm cannot open gui

### ISSUE THREAD

**Issue by newyorkthink** [Slimbook-Team/slimbookbattery#115]
![image](https://github.com/Slimbook-Team/slimbookbattery/assets/87791643/1601e641-aaec-40dd-b0a4-8a9529850821)
![image](https://github.com/Slimbook-Team/slimbookbattery/assets/87791643/58342e0a-110d-4027-a2d3-bc3485d8d654)

i run all command ,but is not work

**Comment by newyorkthink** [comment]
![image](https://github.com/Slimbook-Team/slimbookbattery/assets/87791643/afb5d5a0-b2e3-44c0-b3ea-0644857c07b3)
i not run . is not icon

**Comment by siddhpant** [comment]
Try killing with `$ pkill slimbookbattery` and try running `$ slimbookbattery`.

**Comment by newyorkthink** [comment]
> Try killing with `$ pkill slimbookbattery` and try running `$ slimbookbattery`.

i try but is not work

**Comment by siddhpant** [comment]
"Does not work" does not help. It's a Python script, so errors will be dumped on the terminal, which you should post by copying and pasting.

Also, did you clone the repo and install, or used the packages? The packages are outdated.

**Comment by newyorkthink** [comment]
![image](https://github.com/Slimbook-Team/slimbookbattery/assets/87791643/61056db7-917f-40d3-83ef-98f4488183fb)
i use this

**Comment by newyorkthink** [comment]
please update new version

**Comment by newyorkthink** [comment]
or can you make appimage format

**Comment by newyorkthink** [comment]
![image](https://github.com/Slimbook-Team/slimbookbattery/assets/87791643/6946ce73-f6ee-4321-a4e4-27e212a3c3be)

**Comment by newyorkthink** [comment]
not work

**Comment by siddhpant** [comment]
> or can you make appimage format

There is no need, it's just a python script. One can install by cloning the repo and running `deploy.sh`.

**Comment by siddhpant** [comment]
> ![image](https://github.com/Slimbook-Team/slimbookbattery/assets/87791643/6946ce73-f6ee-4321-a4e4-27e212a3c3be)
> 

Hmm, so it keeps running in background? What does `ps` say? I don't know much about the internal working yet, I suppose it is running and the icon doesn't show up on i3? What about GNOME? 

Otherwise you probably could disable the autostart / service and try again after reboot.

**Comment by newyorkthink** [comment]
> > ![image](https://user-images.githubusercontent.com/87791643/256151446-6946ce73-f6ee-4321-a4e4-27e212a3c3be.png)
> 
> Hmm, so it keeps running in background? What does `ps` say? I don't know much about the internal working yet, I suppose it is running and the icon doesn't show up on i3? What about GNOME?
> 
> Otherwise you probably could disable the autostart / service and try again after reboot.

i try everything, is not runing in background , but is always show is in execution , and i try everything, the icon is not show in i3wm

**Comment by siddhpant** [comment]
Did you update to the latest version? There was a bug fix for pgrep which was merged after 4.0.8.

**Comment by siddhpant** [comment]
#110 describes the same problem, and the same thing is mentioned — use the latest version from git. 

Please search issues before opening a new one.

**Comment by MarSlimbook** [comment]
Here is the release [v4.0.9beta](https://github.com/Slimbook-Team/slimbookbattery/releases/tag/v4.0.9beta)
I'll close this issue and keep the original one.

**Comment by MarSlimbook** [comment]
If you want a quick fix for arch this is the commit that should fix the issue:
https://github.com/Slimbook-Team/slimbookbattery/commit/228365ec3cc71816c3bc20d3e3b3b41379e779f3
Just edit /usr/bin/slimbookbattery and correct the pgrep command call

**Comment by ClashC** [comment]
> Here is the release [v4.0.9beta](https://github.com/Slimbook-Team/slimbookbattery/releases/tag/v4.0.9beta) I'll close this issue and keep the original one.

Thank you very much! For info, this version works here compared to the 4.0.8beta on Linux Mint 22
