### ISSUE TITLE
About version

### ISSUE THREAD

**Issue by ehooo** [Slimbook-Team/slimbookbattery#18]
Hello,

I see that the version on the file slimbookbattery.desktop is not the same that have on the changelog file.

What must be the version showing on the --version option?

Now is taking from the changelog, but i'm not sure if the proper file is that or must be the desktop one.

**Comment by slimbook** [comment]
Well I also think it is more correct to take it from desktop file. Changelog file is always up to date and as you can see we sometimes forget to update the desktop file, that's why we chose changelog. But desktop file should be up to date so lets use it :)
