### ISSUE TITLE
Window too tall, can't save changes

### ISSUE THREAD

**Issue by Pizzacutter-at-tty3** [Slimbook-Team/slimbookbattery#20]
Hi, the window where preferences are set is too big to be displayed properly at 1366x768 displays. Buttons on the bottom are clickable, but I can't see what they say until I move the windows with a shortcut key (XFCE 4.14). Although, the most important issue is that the accept button does not do anything and it's impossible to save my changes. The old window worker better, this also seems a bit overstyled for my taste.
Version that I have installed is 4.0.2

**Comment by madmanRB** [comment]
Yeah I have the same issue, the UI cant be resized and is unusable...

what a terrible UI choice! They need to go back to the old UI because that could get resized easily.
I am reverting to the old version personally or use tlp-ui instead.

This was clearly remade with hidpi in mind but some of us use this for rescuing old laptops from the trash heap.

**Comment by slimbook** [comment]
Well that's true, we are still looking to improve the GUI, we don't know either if there is an option to scale a window with all widgets, but talking about the accept button, does the program throw any exception when you click it or when you use the shortcut?
I will update testing version soon to try if works fine in smaller resolutions.

**Comment by Pizzacutter-at-tty3** [comment]
The button doesn't do anything at all, no exceptions

**Comment by madmanRB** [comment]
Yeah I cant do anything whatsoever, its useless in its current state for anything less than 1440P and my laptop monitor only goes up to 1366x786.

If the app cant be resized at least remove the padding and or move the confirmation stuff to the top of the app.

**Comment by slimbook** [comment]
Try this [Version 4.0.3](https://github.com/slimbook/slimbookbattery/releases/tag/v4.0.3beta), it should work as a quick fix.

**Comment by madmanRB** [comment]
Yeah thats way better, at least for my screen

**Comment by Freeplayg** [comment]
I've tried 4.0.3 but it seems to not be launching at all? I'm on Pop! OS 21.04

**Comment by PacoMoraMartin** [comment]
@Freeplayg can you open it in terminal and share the output? Why did you choose this issue, is it related to your resolution?

**Comment by slimbook** [comment]
@Freeplayg  can you open it in terminal and share the output? Why did you choose this issue, is it related to your resolution?

**Comment by Freeplayg** [comment]
I'm having the same issue as the OP w/ the window being too big:
![Screenshot from 2021-10-18 18-48-25](https://user-images.githubusercontent.com/40742947/138277699-0c9af71e-ea8d-4f16-a409-ad39e15a14a8.png)

Sorry I'm still kind of new to Linux, how do I run it from the terminal?

**Comment by slimbook** [comment]
Hi, good to hear that! Usually you can search for 'terminal' in the applications menu or use the shortcut ctrl+alt+t (in most of the systems), then type 'slimbookbattery' and then enter.
Can yo provide your resolution values ?

**Comment by Freeplayg** [comment]
`python3: can't open file '/usr/bin/../src/slimbookbatterypreferences.py': [Errno 2] No such file or directory` Is what I get

>  Can yo provide your resolution values ?

If you mean display resolution, It's 1366x768

**Comment by slimbook** [comment]
> `python3: can't open file '/usr/bin/../src/slimbookbatterypreferences.py': [Errno 2] No such file or directory` Is what I get

Okey, this should be fixed. Thanks for reporting, tell us if window size is better now

**Comment by Freeplayg** [comment]
Works now!
![Screenshot from 2021-10-25 08-46-22](https://user-images.githubusercontent.com/40742947/138697740-92e2a680-bd97-4535-9be4-0d65905a7ce0.png)

**Comment by slimbook** [comment]
Well, could you please share terminal output? two tabs are not showing, it might show why. Thanks!

**Comment by Freeplayg** [comment]
![Screenshot from 2021-10-25 17-51-49](https://user-images.githubusercontent.com/40742947/138776260-1d53e011-3973-4e3f-b166-d15b8daca208.png)

**Comment by udenizdemirbilek** [comment]
Hello and thank you for this program that lets me use my 8 year old laptop!
I also encountered problems with the Accept button,
all my profiles are stuck to graphics card saving profile and I can't change the settings!
I'm attaching a video and my report file,
Also the following appears on the terminal when I click on the accept button

Lastly, I see you use Python for the program and was wondering if there's anything I can do to help, (I'm a novice programmer)

Take care!

![Screenshot from 2021-10-29 22-37-39](https://user-images.githubusercontent.com/81304552/139492596-1348700b-981b-4f4e-bf47-2b1b17f1f0b2.png)
[report_29-10-21_22:24.txt](https://github.com/slimbook/slimbookbattery/files/7444458/report_29-10-21_22.24.txt)

https://user-images.githubusercontent.com/81304552/139492079-cb5a0680-e580-44e9-b982-a46bbb49bf3b.mp4

**Comment by slimbook** [comment]
Hi, thanks for reporting, your issue is related to [#21 ](https://github.com/slimbook/slimbookbattery/issues/21), the testing version, which will be released soon,  should fix it. Of course you can take a look at the code and [to do list](https://github.com/slimbook/slimbookbattery/projects/1#card-71584259) ;)

**Comment by slimbook** [comment]
New version released
