### ISSUE TITLE
Application Won't Turn On

### ISSUE THREAD

**Issue by JosephReza** [Slimbook-Team/slimbookbattery#21]
Hello,

I recently installed Slimbook Battery version 4.0.1-3 from the AUR on Arch Linux on a 2014 Lenovo z50-70 with an Intel i7-4510U (4) @ 2.100GHz. I get the following errors when running the application and clicking Accept:

Without sudo:
```
`[joseph@z50-70 ~]$ slimbookbattery
Language:  en_US
Full window is displayed
Width: 1920  Height: 1080
model name      : Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
Intel
TDP Controller: slimbookintelcontroller
TDP Controller not installed
['en_US']

Loading variables ...

        State: on
        Autostart: on
        Mode: Medium
        WorkMode:  AC
        Icon: on

LOADING LOW MODE COMPONENTS ...

LOADING BALANCED MODE COMPONENTS ...

LOADING HIGH MODE COMPONENTS ...

Closing window ...
        State: on
        Autostart: on
        Mode: Mid

Switch alerts: False

['AHORRODEENERGIA' CONFIGURATION]
Setting limit to maximum --> Exit: 0
Traceback (most recent call last):
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 3938, in close_ok
    self.apply_conf()
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 4075, in apply_conf
    self.write_modes_conf()
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 3170, in write_modes_conf
    statGovernor = self.comboBoxGovernor.get_active_iter()  # .conf file && Tlp custom file*
AttributeError: 'Preferences' object has no attribute 'comboBoxGovernor'`
```

With sudo:
```
`[joseph@z50-70 ~]$ sudo slimbookbattery
Language:  en_US
Full window is displayed
Copiying configuration files ...
Width: 1920  Height: 1080
'TDP'

Closing window ...
        State: on
        Autostart: off
Err: Could not get mode
Traceback (most recent call last):
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 3938, in close_ok
    self.apply_conf()
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 4035, in apply_conf
    config.set('CONFIGURATION', 'plug_warn', '0')
  File "/usr/lib/python3.9/configparser.py", line 1204, in set
    super().set(section, option, value)
  File "/usr/lib/python3.9/configparser.py", line 902, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'CONFIGURATION'`
```

I am not sure if this is a packaging issue and I should post in the AUR forum or if it's an issue with the application itself and I should post here, so forgive me if it was an issue with packaging.

**Comment by slimbook** [comment]
Hi, could you please show me the output of:
`for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_driver; do cat $i; done`

It seems to be a problem with governor compatibility. Your governor might not be supported.

**Comment by JosephReza** [comment]
Apologies for not responding sooner. 
`[joseph@z50-70 ~]$ for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_driver; do cat $i; done
intel_cpufreq
intel_cpufreq
intel_cpufreq
intel_cpufreq
`

That being said, it works now so there's no issue anymore on my end, but I'll leave the issue open in case someone else has the same issue.

**Comment by slimbook** [comment]
Okey, thank you, we also added that governor for future versions. :)

**Comment by Aminmalek** [comment]
I have the same problem on Ubuntu 20.04!

**Comment by slimbook** [comment]
Hi @Aminmalek, could you please try the testing version [here](https://github.com/slimbook/slimbookbattery/releases)? It should fix the problem.

**Comment by Aminmalek** [comment]
Hi, i have installed this by nothing is run and it's just a raw icon

**Comment by slimbook** [comment]
@Aminmalek is the terminal output of the error above like yours?, upload it together with some screenshots if possible (may be useful too), thank you!

**Comment by Aminmalek** [comment]
> @Aminmalek is the terminal output of the error above like yours?, upload it together with some screenshots if possible (may be useful too), thank you!

I have 2 kind of  errors in 2 versions, which one should I send?

**Comment by slimbook** [comment]
The newest version one
