### ISSUE TITLE
starting from terminal as minimized

### ISSUE THREAD

**Issue by the-nexi** [Slimbook-Team/slimbookbattery#24]
Hello! I run slimbookbattery via i3 window manager, version 4 launches with the interface wide-open. Please add a command line argument like "slimbookbattery --minimize" to launch the software only in the tray

**Comment by slimbook** [comment]
If you only want to launch the indicator, then you should use 'python3 /usr/share/slimbookbattery/slimbookbatteryindicator.py', 'slimbookbattery' launches preferences window

**Comment by slimbook** [comment]
Thank you @ehooo [Test 4.0.3](https://github.com/slimbook/slimbookbattery/releases/tag/v4.0.3beta)

**Comment by the-nexi** [comment]
> python3 /usr/share/slimbookbattery/slimbookbatteryindicator.py

Thanks, closing the issue then
