### ISSUE TITLE
Impossible to save custom parameters

### ISSUE THREAD

**Issue by Pm38110** [Slimbook-Team/slimbookbattery#26]
Hi,
thank you for the new version of Slimbook Battery.
I am on Ubuntu 20.04 LTS.
I have an issue, when I want to change le luminosity level of the 3 modes (saving/balanced/perofrmences), I click on "accept".
Parameters aren't saving.
When I launch again the advanced mode, I find the defaut parameters  each time.

**Comment by slimbook** [comment]
Hi @Pm38110, 
Please try executing the program on terminal <---(slimbookbattery), and share the result. 
Does the app close when you click the accept button?

**Comment by Pm38110** [comment]
Hi,

thank you for your reply.
I have launched Slimbookbattery in commad line.
I had the same graphic interface.
I have tried to modify luminosity level and click on "accept".
Nothing appears, the app doesn't close and parameters aren't saved.
Thank you for your help.

**Comment by Carlosmape** [comment]
I had that error first time I migrated from older SlimbookBattery version. 
Using script developed in (#30) may solve this trouble

**Comment by slimbook** [comment]
Try installing the testing version [4.0.3beta](https://github.com/slimbook/slimbookbattery/releases/tag/v4.0.3beta)  and tell us if fixes the problem

**Comment by Pm38110** [comment]
Good evening,
it works perfectly now !
Thank you


*Pascal*



Le lun. 25 oct. 2021 à 13:50, SLIMBOOK TEAM ***@***.***> a
écrit :
