### ISSUE TITLE
Split preference by tab

### ISSUE THREAD

**Issue by ehooo** [Slimbook-Team/slimbookbattery#31]
I think is better way to manage the app if we split the preference code in multples classes, one per tab.

**Comment by slimbook** [comment]
Yes! It's something I had in mind many time ago ([To do](https://github.com/slimbook/slimbookbattery/projects/1#card-66992371)) Thank you so much!

**Comment by ehooo** [comment]
Hello @slimbook 
I have some questions about "save energy" tab:

* The option list for "CPU scaling governor saving profile:"
Only choose [one option](https://github.com/slimbook/slimbookbattery/blob/main/src/slimbookbatterypreferences.py#L1111) and it not depend of the "governor driver" and allways is the same, however on the others tabs in case of [its depends of the driver](https://github.com/slimbook/slimbookbattery/blob/main/src/slimbookbatterypreferences.py#L1593).

Also the function [governorIsCompatible](https://github.com/slimbook/slimbookbattery/blob/main/src/slimbookbatterypreferences.py#L3776) there is other type of driver "intel_cpufreq" but any list is related with that driver.

Could you clarify that point?
Thanks in advance.

**Comment by slimbook** [comment]
Hi @ehooo, we used that option because is the only one that saves energy (for the energy saving mode) and it does not depend on any driver because is available in all of them. What dou you think, should we add the selection too? 

On the other hand, it's true, I only added it to the [check_autostart_Governor function](https://github.com/slimbook/slimbookbattery/blob/main/src/slimbookbatterypreferences.py#L2744) but i forgot to add it to the combobox list generation, I'll update it now :)

**Comment by ehooo** [comment]
Hello @slimbook 
For me the issue here is that the value for `powersave` in Intel is 1 but in acpi is 3.
By the way I think that better options is show the same in all tabs, and the user should be how choose on or the other

**Comment by ehooo** [comment]
@slimbook could you take a look the [commit](https://github.com/ehooo/slimbookbattery/commit/7f151f92d387b9fb1e94e7e96eae5ad939536021) in order to see if you like the new class SettingsGrid?
The idea is create the class with parameters 'ahorrodeenergia', 'equilibrado' or 'maximorendimiento'.
The next commit will have all changes for the tabs 'equilibrado' and 'maximorendimiento', so the PR could have a lot changes.

**Comment by slimbook** [comment]
Looks great! I had also thougth of changing the names to 'energysaving', 'balanced' and 'high'

**Comment by ehooo** [comment]
Hi @slimbook the name are the same that the files refered, in order to simpliflly the mapping.

**Comment by slimbook** [comment]
> Hello @slimbook For me the issue here is that the value for `powersave` in Intel is 1 but in acpi is 3. By the way I think that better options is show the same in all tabs, and the user should be how choose on or the other

Yes, better for customization, we just have to set as default value 'powersave'

**Comment by slimbook** [comment]
> Hi @slimbook the name are the same that the files refered, in order to simpliflly the mapping.

Yes, I know, that was the idea, those files would also be renamed, but this is not important now, we can do it when everything is done.
PD: I'm going to test the mode settings class in the testing branch

**Comment by ehooo** [comment]
@slimbook i think that with the last PR this issue is completed.

**Comment by slimbook** [comment]
Yes, you did a great work! (learned a lot), I will close this issue and start testing, thank you so much!!
