### ISSUE TITLE
Suport change from theme shceme colors to app scheme

### ISSUE THREAD

**Issue by oriolpiera** [Slimbook-Team/slimbookbattery#36]
* OS: Ubuntu 20.04
* GUI: Mate
* Theme: Ambiant-Mate

![image](https://user-images.githubusercontent.com/26488435/138655435-3fe8c53c-4a6e-47c0-95a6-7b2957d1c013.png)

It seems that the application get the scheme colors from theme. In my scenario, the theme doesn't seems to get well with the app.
It may be a good point to be able to switch between them scheme to app scheme.

**Comment by ehooo** [comment]
I think this issue is solved on the last version
![image](https://user-images.githubusercontent.com/709565/140234400-6bf1fe68-e3ca-4476-b2bc-6fe0f89723ad.png)

But i see that the cross is not visible on the light view.
![image](https://user-images.githubusercontent.com/709565/140234300-38cc83ff-642c-4062-8124-70fbd303c5eb.png)

**Comment by oriolpiera** [comment]
Hi @ehooo 

I recently updated to 4.0.3 and I can't see the "system style" flag. Could you tell me in which tab is it?

Thanks,

![image](https://user-images.githubusercontent.com/26488435/140282815-23206c04-67a6-4f99-b9f8-60079171c894.png)

**Comment by PacoMoraMartin** [comment]
Yes, the deb file is not updated yet, I'm on it. Also have to edit those images to match dark and light themes :)
You might have to remove the application to install the updated one, because the version is not changing.

**Comment by slimbook** [comment]
That's true, the .deb file has not been updated yet, I'm doing it now (Also have to update images to match dark and light themes), you might have to uninstall the app to install the new updated one, because version is still 4.0.3

**Comment by slimbook** [comment]
@oriolpiera you can try it now [here](https://github.com/slimbook/slimbookbattery/releases/tag/v4.0.3beta)!

**Comment by oriolpiera** [comment]
It works!! Both themes (default and system theme) looks greate!!!

Thanks


![image](https://user-images.githubusercontent.com/26488435/140372578-31a81512-a115-40a7-af94-d6f059426f86.png)

![image](https://user-images.githubusercontent.com/26488435/140372858-40de069d-a884-4f44-9898-3dff0730390f.png)
