### ISSUE TITLE
Can't access the bottom buttons in small resolutions

### ISSUE THREAD

**Issue by UbayGD** [Slimbook-Team/slimbookbattery#4]
Testing on my Thinkpad X220, which has a resolution of 1366x768, I found that the bottom buttons are not accessible, so changes cannot be applied. Perhaps this could be made more responsive.

I don't know how much of a priority this might be as the most common resolution nowadays is FullHD or if it's worth fixing.

![captura_slimbook_battery](https://user-images.githubusercontent.com/10211264/132944966-d83d85e7-a674-4dd3-b280-8937dfd442b8.png)

**Comment by slimbook** [comment]
Hi @UbayGD , can you test it now?,  the window should be smaller in your laptop

**Comment by UbayGD** [comment]
I just tried it now and I can see the buttons. Thank you very much for your help @slimbook !!!

**Comment by slimbook** [comment]
You are welcome!
