### ISSUE TITLE
Can't import modules with homebrew 

### ISSUE THREAD

**Issue by MarSlimbook** [Slimbook-Team/slimbookbattery#55]
I have the same problem on Ubuntu 20.04!

_Originally posted by @Aminmalek in https://github.com/slimbook/slimbookbattery/issues/21#issuecomment-963475331_

**Comment by MarSlimbook** [comment]
@Aminmalek could you share the new error log here?

**Comment by bilalbayasut** [comment]
when running on terminal , it said 
```
ModuleNotFoundError: No module named 'gi'
```

**Comment by MarSlimbook** [comment]
Hi @bilalbayasut try installing the dependency 'libgirepository-1.0-1', it is marked as a dependency so, did you installed it from the repository using apt? In that case, which distro are you using?

**Comment by Aminmalek** [comment]
2021-11-22 19:23:30,330 - 665 - INFO - Intel detected
2021-11-22 19:23:30,338 - 690 - ERROR - TDP Controller not installed
in this new version(4.0.3) I can save the setting but nothing happens even brightness level doesn't change.

**Comment by slimbook** [comment]
@Aminmalek, Is that the only output you get from the terminal? Could you generate a report (in the info window) and send it to us. The error of 'TDP controller not installed' does not stop the app.

**Comment by bilalbayasut** [comment]
> Hi @bilalbayasut try installing the dependency 'libgirepository-1.0-1', it is marked as a dependency so, did you installed it from the repository using apt? In that case, which distro are you using?

xubuntu, I gave up, ended up installing ubuntu and it worked fine. thanks for your reply

**Comment by slimbook** [comment]
Well, I have not been able to reproduce this issue yet, i will leave this issue open to see if someone has the same problem.

**Comment by dkocich** [comment]
I have the same issue, start in the terminal shows only an import problem even though I installed the APT package. I guess it is caused by multiple versions of python3 in the system.

❯ slimbookbattery
Traceback (most recent call last):
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 21, in <module>
    import gi

**Comment by slimbook** [comment]
Hi, could you check if you have installed python3-gi?

**Comment by slimbook** [comment]
Can't repro

**Comment by dkocich** [comment]
@slimbook I tried again with beta
![image](https://user-images.githubusercontent.com/6165660/174565151-8a4b5006-c94b-493f-827d-55cac22869ab.png) - still the same issue appears in the terminal

![image](https://user-images.githubusercontent.com/6165660/174565289-846bef5f-79fc-4de2-8855-9b093d27068c.png)

i see pytgon-gi in my system packages
![image](https://user-images.githubusercontent.com/6165660/174565056-b13eb3aa-15ba-4d54-9ac3-7d4d8dd1179b.png)

so I checked that my python is from linuxbrew - not using system packages...
![image](https://user-images.githubusercontent.com/6165660/174565473-e2c58d5c-a364-4008-938b-1f195c966cd8.png)

**Comment by slimbook** [comment]
Hi, so you are using Homebrew.
Check this: [Hebrew Docs](https://docs.brew.sh/Homebrew-on-Linux) and [Homebrew-and-Python](https://docs.brew.sh/Homebrew-and-Python)
Specially check if you did this:

> Follow the Next steps instructions to add Homebrew to your PATH and to your bash shell profile script, either ~/.profile on Debian/Ubuntu or ~/.bash_profile on CentOS/Fedora/Red Hat.


```
test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
test -r ~/.bash_profile && echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.bash_profile
echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.profile

```
This [StackOverlfow Issue](https://stackoverflow.com/questions/63246697/importing-modules-installed-via-homebrew-into-python) might also be helpful.
I'll try to take a closer look when I have some time.
