### ISSUE TITLE
Taskbar icon way too big

### ISSUE THREAD

**Issue by logileifs** [Slimbook-Team/slimbookbattery#56]
This is how the taskbar icon looks after the latest release (4.0.3)
![image](https://user-images.githubusercontent.com/2317815/142735511-427ee0a7-3c0d-47eb-adba-fe82b077c1ad.png)

I'm using 18.04.1-Ubuntu Budgie.
One thing I want to add as well, the old UI looked so much better, this new style is just way too much.

**Comment by MarSlimbook** [comment]
Seems that this desktop indicator panel does not resize images, we will update as soon as we find a solution. Seems that converting to svg could work. Does the off button show in the same size?

**Comment by KavinAVS** [comment]
Yes, the off button is the same size.

![Screenshot from 2021-12-12 11-14-04](https://user-images.githubusercontent.com/25111483/145720163-74995fcb-daba-45f4-a521-d6042aa953fd.png)

**Comment by slimbook** [comment]
Hi, @KavinAVS @logileifs check this [testing version](https://github.com/slimbook/slimbookbattery/releases/tag/Test).

**Comment by slimbook** [comment]
Referenced to #62
