### ISSUE TITLE
Lets create a bug template for bug reporting

### ISSUE THREAD

**Issue by ehooo** [Slimbook-Team/slimbookbattery#58]
I think could be good idea create a [issue templates](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) for bugs.

@slimbook @MarSlimbook what do you think about? i cannot access to settings to set it up.

**Comment by MarSlimbook** [comment]
Of course, it's a good idea!
I did it, it's quite basic but, it will be updated if it's required more information
