### ISSUE TITLE
appIndicator/systray icons size for big screen resolutions

### ISSUE THREAD

**Issue by gentooza** [Slimbook-Team/slimbookbattery#62]
**Describe the bug**
Hi, I find the systray icons of slimbookbattery too big in the system tray, when using Mate in a slimbook executive 14 computer.
(2880x1800px)
A workaround for me is to manually overwrite: /usr/share/slimbookbattery/images/indicator/... png icons from 96x96px to 20x20px.
But I guess it should be adaptable. (vectorial?)

**To Reproduce**
I manually installed slimbookOs, and afterwards installed the ubuntu-mate-desktop flavour.

**Desktop (please complete the following information):**
 - OS: SlimbookOS
 - Version: 20.04
 - Desktop Environment: Mate

**Expected behavior (Optional)**
Icons in systray should be adaptable to screen resolution.

**Screenshots**
![big_icon](https://user-images.githubusercontent.com/10772286/150735176-009d7e76-6db2-42e7-9fe8-380bc79a5519.png)
![small icons](https://user-images.githubusercontent.com/10772286/150735188-b39f7723-f6a5-43ba-a088-fddfe2597d03.png)

**Additional context**

**Comment by slimbook** [comment]
Hi @gentooza, can you try this [testing version](https://github.com/slimbook/slimbookbattery/releases), it should fix this issue.

**Comment by gentooza** [comment]
Hi!

Sorry, I didn't see #56

Yes, with the testing version icons are now 24x24 and fit perfectly.
When will be public in repo?

 thanks a lot!
