### ISSUE TITLE
Issue CPU scaling on AC. 

### ISSUE THREAD

**Issue by FedericoCalzoni** [Slimbook-Team/slimbookbattery#65]
**Describe the bug**
When laptop is in AC, due to the absence of a parameter:
CPU_SCALING_GOVERNOR_ON_AC =
which is written by slimbookbattery inside the tlp.conf file, the governor cannot be changed.

This is a problem because it makes it impossible to set a governor for when it is in AC and when it is in BAT.
This is because tlp.conf is the last configuration file to be read, and overwrites the others.

**To Reproduce**
1. on BAT: set Energy Saving from slimbookbattery .(now the governor is "powersave"
2. plug AC, the governor is still powersave, even if I wrote in the tlp.conf CPU_SCALING_GOVERNOR_ON_AC = performance. (or even if I wrote this parameter on a config file inside /etc/tlp.d/ )

**Desktop (please complete the following information):**
 - OS: Kubuntu 
 - Version: 21.04
 - Desktop Environment: KDE Plasma

**Expected behavior**
do not unnecessarily modify the parameters that the program should not manage (since it only works when the computer is in BAT mode).

Or instead of use tlp.conf, write the configuration inside a configuration file inside the folder /etc/tlp.d/ so it will be stil possible to edit tlp configuration from the user.

**Comment by FedericoCalzoni** [comment]
In any case the problem can be solved by modifying the 3 slimbookbattery configuration files manually:

They are located in the directory .config/slimbookbattery/custom/

**Comment by slimbook** [comment]
#85
