### ISSUE TITLE
Unable to resize window and access options in the bottom

### ISSUE THREAD

**Issue by Rank-N-Tensor** [Slimbook-Team/slimbookbattery#66]
Hello Slimbook team! I have been using your application for over a year now on my ubuntu 20.04 machine(14'' screen), recently with the new update, I am unable to select the options and slimbook seems to have no effect on my battery levels
![Screenshot from 2022-02-14 23-17-33](https://user-images.githubusercontent.com/85181559/153918754-1acfa5cc-f749-432d-8711-05d938f1bc29.png)
as you can see, I am unable to move the window or resize it to access "cancel", "Restore.." or "accept" options.

**Comment by MarSlimbook** [comment]
Hi @Rank-N-Tensor, could you open it in a terminal? The output should show your screen resolution if it is accessible.

**Comment by Rank-N-Tensor** [comment]
my sincerest apologies, I don't understand what you mean(I'm a beginner). how do I open it in the terminal? for reference, my  screen resolution is 2560x1440 (16:9).

**Comment by Rank-N-Tensor** [comment]
my sincerest apologies, I am able to move the window with the keyboard (Alt+F7 and arrow keys) and can access the options but I'm still unable to resize it. Furthermore, slimbook seems to have no effect on my battery. earlier it would show over 10 hours remaining at 99% and now it's barely 2 hours( same as without slimbook). 
![Screenshot from 2022-02-15 19-50-31](https://user-images.githubusercontent.com/85181559/154080567-1924eba6-de5e-4bfc-a05c-10b23b241baf.png)

lastly,  the options have changed to "low", "medium" and "high"
![Screenshot from 2022-02-15 19-50-35](https://user-images.githubusercontent.com/85181559/154080686-d11e88f1-8952-4c5a-af1a-9c9e12c856e2.png)
it was only after this change that slimbook began behaving unexpectedly. thanks in advance for your time!

**Comment by MarSlimbook** [comment]
> I am able to move the window with the keyboard

Okey, good to know, however, the app should resize automatically, I haven't been able to reproduce this error yet.
I need to check the terminal output to see if something is not working:
- Open a terminal (Ctrl+Alt+T)
- Execute the command 'slimbookbattery' (The app should open)
- Select a different battery mode in the app
- Apply changes

After the app is closed, check the terminal output, It may be long, so copy it and share it with us to check if there is any error in the behaviour of the app.

You can also save the output in a file directly:

- slimbookbattery > /home/(user)/Desktop/myoutput.txt (For example)

**Comment by Rank-N-Tensor** [comment]
apologies for being late, here you go!
```
2022-02-17 20:24:21,461 - 1948 - DEBUG - Loading CSS - original
2022-02-17 20:24:21,496 - 1737 - DEBUG - Full window is displayed
2022-02-17 20:24:21,538 - 1858 - DEBUG - Width: 2560  Height: 1440
2022-02-17 20:24:21,610 - 733 - ERROR - TDP Controller not installed
2022-02-17 20:24:49,447 - 1977 - INFO - Closing window ...

2022-02-17 20:24:49,448 - 1998 - INFO - Rebooting slimbookbatteryindicator.py ...
2022-02-17 20:24:49,485 - 2009 - INFO - Killing process 2703 Exit: 0
2022-02-17 20:24:49,485 - 2013 - INFO - Launching process...
2022-02-17 20:24:49,487 - 2016 - INFO - Done
2022-02-17 20:24:49,487 - 2030 - INFO - 

2022-02-17 20:24:49,488 - 887 - INFO - Mode not setting TDP
2022-02-17 20:24:49,500 - 1498 - INFO - [ahorrodeenergia] Setting DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE saving to "bluetooth" --> Exit(0): 
2022-02-17 20:24:49,512 - 1498 - INFO - [ahorrodeenergia] Setting DEVICES_TO_DISABLE_ON_STARTUP saving to "" --> Exit(0): 
2022-02-17 20:24:49,523 - 1507 - INFO - [ahorrodeenergia] Setting DEVICES_TO_DISABLE_ON_LAN_CONNECT saving to "" --> Exit(0): 
2022-02-17 20:24:49,534 - 1507 - INFO - [ahorrodeenergia] Setting DEVICES_TO_ENABLE_ON_LAN_DISCONNECT saving to "" --> Exit(0): 
2022-02-17 20:24:49,546 - 1498 - INFO - [equilibrado] Setting DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE saving to "bluetooth" --> Exit(0): 
2022-02-17 20:24:49,558 - 1498 - INFO - [equilibrado] Setting DEVICES_TO_DISABLE_ON_STARTUP saving to "" --> Exit(0): 
2022-02-17 20:24:49,569 - 1507 - INFO - [equilibrado] Setting DEVICES_TO_DISABLE_ON_LAN_CONNECT saving to "" --> Exit(0): 
2022-02-17 20:24:49,580 - 1507 - INFO - [equilibrado] Setting DEVICES_TO_ENABLE_ON_LAN_DISCONNECT saving to "" --> Exit(0): 
2022-02-17 20:24:49,592 - 1498 - INFO - [maximorendimiento] Setting DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE saving to "" --> Exit(0): 
2022-02-17 20:24:49,603 - 1498 - INFO - [maximorendimiento] Setting DEVICES_TO_DISABLE_ON_STARTUP saving to "" --> Exit(0): 
2022-02-17 20:24:49,614 - 1507 - INFO - [maximorendimiento] Setting DEVICES_TO_DISABLE_ON_LAN_CONNECT saving to "" --> Exit(0): 
2022-02-17 20:24:49,625 - 1507 - INFO - [maximorendimiento] Setting DEVICES_TO_ENABLE_ON_LAN_DISCONNECT saving to "" --> Exit(0): 
2022-02-17 20:24:49,627 - 1954 - INFO - Setting mode 2 animations
2022-02-17 20:24:49,627 - 1967 - INFO - Animations Active
******************************************************************************
SlimbookBattery-Commandline, executed as: adi
Username: adi - Homedir: /home/adi
Arguments:  apply
Normal power mode

[BRIGTNESS SETTINGS]
/sys/class/backlight exists.
Setting Brightness (mode 2)  to 178 <--> 70 % ... | Exit: 0
Crontab settings added

[TDP SETTINGS]
Battery Mode: 2
TDP Sync not active

[COPY TDP CUSTOM SETTINGS]
2022-02-17 20:24:49,842 - check_plug:263 - INFO - Time since last time disconnection: 1 days
File copied succesfully!
Already set in /etc/tlp.conf
TLP is enabled
******************************************************************************
SlimbookBattery-Commandline, executed as: adi
Username: adi - Homedir: /home/adi
Arguments:  autostart

[BRIGTNESS SETTINGS]
/sys/class/backlight exists.
Setting Brightness (mode 2)  to 178 <--> 70 % ... | Exit: 0
Crontab settings added
******************************************************************************
2022-02-17 20:24:49,989 - __init__:114 - DEBUG - Brightness set
/usr/share/slimbookbattery/src/slimbookbatteryindicator.py:178: DeprecationWarning: Gtk.ImageMenuItem.set_image is deprecated
  item.set_image(icon)
/usr/share/slimbookbattery/src/slimbookbatteryindicator.py:179: DeprecationWarning: Gtk.ImageMenuItem.set_always_show_image is deprecated
  item.set_always_show_image(True)

[MODE SETTINGS]
Detected nvidia graphics profile: intel
Setting new profile ...
Info: the intel profile is already set
Info: selecting the on-demand profile
Writing /lib/modprobe.d/nvidia-runtimepm.conf
Updating the initramfs. Please wait for the operation to complete:
Done
Graphics before --> intel // Graphics after --> on-demand
Required reboot changes to 1
Sudo notify
+ ls /tmp/.X11-unix/X0 /tmp/.X11-unix/X1024 /tmp/.X11-unix/X1025
+ sed s#/tmp/.X11-unix/X##
+ head -n 1
+ display=:0
+ user=adi
+ id -u adi
+ uid=1000
+ sudo -u adi DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send Slimbook Battery Graphics settings have been modified, changes will be applied on restart.
```

**Comment by Rank-N-Tensor** [comment]
the problem here is that earlier, slimbook would show nearly 8-10 hours with the energy saving mode, now its down to 2 hours, for a 100% charge.

**Comment by Rank-N-Tensor** [comment]
another important detail is that im using the 5.11 kernel , as opposed to the 5.13( because of the pixelated screen issue).

**Comment by MarSlimbook** [comment]
> the problem here is that earlier, slimbook would show nearly 8-10 hours with the energy saving mode, now its down to 2 hours, for a 100% charge.
That is a big difference, we will try older versions to check duration. Are you using TLP 1.3?

**Comment by Rank-N-Tensor** [comment]
my sincerest apologies for not following up because I had a major exam. yes I'm using TLP 1.3.1
`--- TLP 1.3.1 --------------------------------------------

+++ Battery Features: Charge Thresholds and Recalibrate
natacpi    = inactive (laptop not supported)
tpacpi-bat = inactive (laptop not supported)
tp-smapi   = inactive (laptop not supported)

+++ Battery Status: BAT0
/sys/class/power_supply/BAT0/manufacturer                   = ASUSTeK
/sys/class/power_supply/BAT0/model_name                     = ASUS Battery
/sys/class/power_supply/BAT0/cycle_count                    = (not supported)
/sys/class/power_supply/BAT0/energy_full_design             =  75998 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  63727 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  50950 [mWh]
/sys/class/power_supply/BAT0/power_now                      =  47483 [mW]
/sys/class/power_supply/BAT0/status                         = Discharging

Charge                                                      =   80.0 [%]
Capacity                                                    =   83.9 [%]` 

furthermore, I'm back to using the `5.13.0-30-generic` kernel. Battery life has not improved :(.

![Screenshot from 2022-03-05 19-11-25](https://user-images.githubusercontent.com/85181559/156885943-60fbf340-4e11-4520-8dc8-33ea59a31a9e.png)

**Comment by Rank-N-Tensor** [comment]
my sincerest apologies for not following up because I had a major exam. yes I'm using TLP 1.3.1
```
--- TLP 1.3.1 --------------------------------------------

+++ Battery Features: Charge Thresholds and Recalibrate
natacpi = inactive (laptop not supported)
tpacpi-bat = inactive (laptop not supported)
tp-smapi = inactive (laptop not supported)

+++ Battery Status: BAT0
/sys/class/power_supply/BAT0/manufacturer = ASUSTeK
/sys/class/power_supply/BAT0/model_name = ASUS Battery
/sys/class/power_supply/BAT0/cycle_count = (not supported)
/sys/class/power_supply/BAT0/energy_full_design = 75998 [mWh]
/sys/class/power_supply/BAT0/energy_full = 63727 [mWh]
/sys/class/power_supply/BAT0/energy_now = 50950 [mWh]
/sys/class/power_supply/BAT0/power_now = 47483 [mW]
/sys/class/power_supply/BAT0/status = Discharging

Charge = 80.0 [%]
Capacity = 83.9 [%]
```

furthermore, I'm back to using the `5.13.0-30-generic kernel`. Battery life has not improved :(.

![Screenshot from 2022-03-05 19-11-25](https://user-images.githubusercontent.com/85181559/156886039-ca706ced-e0d3-4168-a209-4caf196e7e75.png)

**Comment by Rank-N-Tensor** [comment]
hello, ill close this particular issue as the main topic has been solved and open a new one specific to the current issue
