### ISSUE TITLE
configparser.NoSectionError: No section: 'CONFIGURATION'

### ISSUE THREAD

**Issue by w-user** [Slimbook-Team/slimbookbattery#74]
Error arises on system boot with "Crash report" prompt 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - CPU: AMD Ryzen 7 pro 5850u
 
**Screenshots**
![Screenshot from 2022-06-18 17-50-20](https://user-images.githubusercontent.com/82257570/174443827-c64986e5-9d21-4e0a-a7f3-b426dc490b4a.png)

How can I fix it? I'd like to fix it myself with your guidance if you wish and make pull-request.

**Comment by slimbook** [comment]
Hi @w-user, is the preferences window showing correctly?
This is usually caused because the configuration file does not exist. Which can be solved restoring default values in  preferences window.
This file is in /home/<user_name>/.config/slimbookbattery/slimbookbattery.conf

**Comment by w-user** [comment]
The configuration file was in the place and even [CONFIGURATION] section was presented in the file. I tried to restore defaults and crash went away. Not able to reproduce crash now.

**Comment by slimbook** [comment]
So it could be a file permission error, this button also gives reading permission to configuration file. Is everything working correctly now?

**Comment by w-user** [comment]
Yes, everything seems to be working fine. Thank you.
