### ISSUE TITLE
[ENHANCEMENT] Switch modes automatically when AC power cable is plugged and unplugged

### ISSUE THREAD

**Issue by diegolgz** [Slimbook-Team/slimbookbattery#9]
It could be a good idea to let the application switch between modes when the AC power cable is plugged and unplugged.

For example, I would like the application to change to "Performance" mode when I plug the AC power cable in, and switch to "Power save" when I unplug it (or other options, like to leave it as it was).

**Comment by slimbook** [comment]
Well, all options in the first column stop when AC is plugged, although there is an exception; if you have nvidia graphics it will keep the selected graphics mode independently. 
This does not happen with intel and radeon, that work in lower frequencies in case you have chosen graphics saving mode (only on bat). The second column is common so it will work in both modes.
Switching modes when AC could be done with udev rules (changing configuration and rebooting indicator) 
When you refer to leave it as it was,  you mean switching off the application?

**Comment by diegolgz** [comment]
No, I mean the application should remain executing always but I would like something like "actions" when you plug and unplug the AC cable. The options could be "switch mode to <mode>" or "do nothing".

But I know it's hard to define those "actions" or the behaviour.

**Comment by slimbook** [comment]
Well an udev rule could make it, maybe it could be added in the future. We will see ;)
